//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLBPenziskiFond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baza
    {
        public string Tip { get; set; }
        public string Id_Evid { get; set; }
        public string ISIN { get; set; }
        public string Ticker { get; set; }
        public string Nominala { get; set; }
        public int Id { get; set; }
    }
}
