//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLBPenziskiFond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvidencijaAktiva
    {
        public string ISIN { get; set; }
        public string Ticker { get; set; }
        public string Tip_portfelja { get; set; }
        public string Vrsta_portfelja { get; set; }
        public string Tip { get; set; }
        public string Naziv_instrumenta { get; set; }
        public string Trz { get; set; }
        public string Nominala { get; set; }
        public Nullable<double> Polje_9 { get; set; }
        public Nullable<double> Izn_serije { get; set; }
        public Nullable<double> Multiplikator { get; set; }
        public Nullable<System.DateTime> Datum_izdavanja { get; set; }
        public string Datum_dospijeza { get; set; }
        public string Konvencija_dana { get; set; }
        public string Rocnost_instrumenta { get; set; }
        public string Funkcija_izracuna { get; set; }
        public string Kotacija_instrumenta { get; set; }
        public string Short_Sell { get; set; }
        public string Frequency { get; set; }
        public string Kupon { get; set; }
        public string Vrsta_prinosa { get; set; }
        public string Objekt_reval { get; set; }
        public string Yield { get; set; }
        public string Vr_cijene { get; set; }
        public string Fond { get; set; }
        public Nullable<double> Evid_Id { get; set; }
        public Nullable<System.DateTime> Uneseno { get; set; }
        public string Korisnik { get; set; }
        public string Izdavatelj { get; set; }
        public string Polje_30 { get; set; }
        public string Opis { get; set; }
        public string Sifra_podatka { get; set; }
        public string Polje_33 { get; set; }
        public string CFI_oznaka { get; set; }
        public string Polje_35 { get; set; }
        public string Vrsta_uloga { get; set; }
        public string Polje_37 { get; set; }
        public string Polje_38 { get; set; }
        public string Polje_39 { get; set; }
        public string Status_aut { get; set; }
        public string Polje_41 { get; set; }
        public int Id { get; set; }
    }
}
