//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLBPenziskiFond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruments
    {
        public int Id { get; set; }
        public string Isin { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Currency { get; set; }
        public string Type { get; set; }
        public string Country { get; set; }
        public string Sector { get; set; }
        public Nullable<decimal> Total_Yield { get; set; }
        public Nullable<decimal> Total_Yield_Currency { get; set; }
        public Nullable<decimal> Price_Yield_Currency { get; set; }
        public Nullable<decimal> Dividend_Yield { get; set; }
        public Nullable<decimal> Dividend_Yield_Currency { get; set; }
        public Nullable<decimal> Price_Yield { get; set; }
        public Nullable<decimal> Share { get; set; }
        public string Full_Name { get; set; }
    }
}
