//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLBPenziskiFond.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLBEntities : DbContext
    {
        public NLBEntities()
            : base("name=NLBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EksportObjekti> EksportObjekti { get; set; }
        public virtual DbSet<DnevniPrinosi> DnevniPrinosi { get; set; }
        public virtual DbSet<EksportPrihodi> EksportPrihodi { get; set; }
        public virtual DbSet<AktivniDatumi> AktivniDatumi { get; set; }
        public virtual DbSet<Baza> Baza { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Akcii_Cenoven> Akcii_Cenoven { get; set; }
        public virtual DbSet<Akcii_Dividenden> Akcii_Dividenden { get; set; }
        public virtual DbSet<EvidencijaAktiva> EvidencijaAktiva { get; set; }
        public virtual DbSet<Registers> Registers { get; set; }
        public virtual DbSet<Numerators> Numerators { get; set; }
        public virtual DbSet<Registers_Numerators> Registers_Numerators { get; set; }
        public virtual DbSet<Denominators> Denominators { get; set; }
        public virtual DbSet<Shares> Shares { get; set; }
        public virtual DbSet<Registers_Yields> Registers_Yields { get; set; }
        public virtual DbSet<Total_Yields> Total_Yields { get; set; }
        public virtual DbSet<Registers_Yields_Denominators> Registers_Yields_Denominators { get; set; }
        public virtual DbSet<Yields_Denominators> Yields_Denominators { get; set; }
        public virtual DbSet<Registers_Dividend_Yields_Numerators> Registers_Dividend_Yields_Numerators { get; set; }
        public virtual DbSet<Registers_Price_Yields_Numerators> Registers_Price_Yields_Numerators { get; set; }
        public virtual DbSet<Registers_Total_Yields_Numerators> Registers_Total_Yields_Numerators { get; set; }
        public virtual DbSet<Record_Assets> Record_Assets { get; set; }
        public virtual DbSet<Price_Yields> Price_Yields { get; set; }
        public virtual DbSet<Dividend_Yields> Dividend_Yields { get; set; }
        public virtual DbSet<Instruments> Instruments { get; set; }
    }
}
