//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLBPenziskiFond.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_Assets
    {
        public int Id { get; set; }
        public string Isin { get; set; }
        public string Id_Record { get; set; }
        public string Ticker { get; set; }
        public string Type { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public string Full_Name { get; set; }
        public string Sector { get; set; }
        public string Country { get; set; }
    }
}
